#!/usr/bin/expect -f

log_user 0

set timeout 3

set commandstring [join [lrange $argv 0 [llength $argv]] " "]

spawn /bin/bash
expect {
  -re ".*\$ *$" {
    send "$commandstring\r"
  }
  timeout { exit 1 }
}
expect {
  -re {Enter passphrase: *} {
    send "$env(REAPER_KEY_PASSWORD)\r"
  }
  timeout { exit 2 }
}
expect {
  -re {\$ *} {
    send "exit $?\rexit $?\r"
  }
  timeout { exit 3 }
}
expect eof
